//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Pocketsphinx {

public class Segment : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Segment(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Segment obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Segment() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pocketsphinxPINVOKE.delete_Segment(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

    public override string ToString() {
	return Word + " " + StartFrame + " " + EndFrame + " " + Prob;
    }

  public string Word {
    set {
      pocketsphinxPINVOKE.Segment_Word_set(swigCPtr, value);
    } 
    get {
      string ret = pocketsphinxPINVOKE.Segment_Word_get(swigCPtr);
      return ret;
    } 
  }

  public int Ascore {
    set {
      pocketsphinxPINVOKE.Segment_Ascore_set(swigCPtr, value);
    } 
    get {
      int ret = pocketsphinxPINVOKE.Segment_Ascore_get(swigCPtr);
      return ret;
    } 
  }

  public int Lscore {
    set {
      pocketsphinxPINVOKE.Segment_Lscore_set(swigCPtr, value);
    } 
    get {
      int ret = pocketsphinxPINVOKE.Segment_Lscore_get(swigCPtr);
      return ret;
    } 
  }

  public int Lback {
    set {
      pocketsphinxPINVOKE.Segment_Lback_set(swigCPtr, value);
    } 
    get {
      int ret = pocketsphinxPINVOKE.Segment_Lback_get(swigCPtr);
      return ret;
    } 
  }

  public int Prob {
    set {
      pocketsphinxPINVOKE.Segment_Prob_set(swigCPtr, value);
    } 
    get {
      int ret = pocketsphinxPINVOKE.Segment_Prob_get(swigCPtr);
      return ret;
    } 
  }

  public int StartFrame {
    set {
      pocketsphinxPINVOKE.Segment_StartFrame_set(swigCPtr, value);
    } 
    get {
      int ret = pocketsphinxPINVOKE.Segment_StartFrame_get(swigCPtr);
      return ret;
    } 
  }

  public int EndFrame {
    set {
      pocketsphinxPINVOKE.Segment_EndFrame_set(swigCPtr, value);
    } 
    get {
      int ret = pocketsphinxPINVOKE.Segment_EndFrame_get(swigCPtr);
      return ret;
    } 
  }

  public static Segment FromIter(SWIGTYPE_p_void itor) {
    global::System.IntPtr cPtr = pocketsphinxPINVOKE.Segment_FromIter(SWIGTYPE_p_void.getCPtr(itor));
    Segment ret = (cPtr == global::System.IntPtr.Zero) ? null : new Segment(cPtr, false);
    return ret;
  }

  public Segment() : this(pocketsphinxPINVOKE.new_Segment(), true) {
  }

}

}
