//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Pocketsphinx {

class SphinxBasePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="SWIGRegisterExceptionCallbacks_SphinxBase")]
    public static extern void SWIGRegisterExceptionCallbacks_SphinxBase(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_SphinxBase")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_SphinxBase(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_SphinxBase(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_SphinxBase(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(SphinxBasePINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(SphinxBasePINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="SWIGRegisterStringCallback_SphinxBase")]
    public static extern void SWIGRegisterStringCallback_SphinxBase(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_SphinxBase(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static SphinxBasePINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_delete_Config")]
  public static extern void delete_Config(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_Config_SetBoolean")]
  public static extern void Config_SetBoolean(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_Config_SetInt")]
  public static extern void Config_SetInt(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_Config_SetFloat")]
  public static extern void Config_SetFloat(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_Config_SetString")]
  public static extern void Config_SetString(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_Config_SetStringExtra")]
  public static extern void Config_SetStringExtra(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_Config_Exists")]
  public static extern bool Config_Exists(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_Config_GetBoolean")]
  public static extern bool Config_GetBoolean(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_Config_GetInt")]
  public static extern int Config_GetInt(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_Config_GetFloat")]
  public static extern double Config_GetFloat(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_Config_GetString")]
  public static extern string Config_GetString(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_new_FrontEnd")]
  public static extern global::System.IntPtr new_FrontEnd();

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_delete_FrontEnd")]
  public static extern void delete_FrontEnd(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_FrontEnd_OutputSize")]
  public static extern int FrontEnd_OutputSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_FrontEnd_ProcessUtt")]
  public static extern int FrontEnd_ProcessUtt(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, uint jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_delete_Feature")]
  public static extern void delete_Feature(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_new_Feature")]
  public static extern global::System.IntPtr new_Feature();

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_new_FsgModel__SWIG_0")]
  public static extern global::System.IntPtr new_FsgModel__SWIG_0(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, float jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_new_FsgModel__SWIG_1")]
  public static extern global::System.IntPtr new_FsgModel__SWIG_1(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_delete_FsgModel")]
  public static extern void delete_FsgModel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_FsgModel_WordId")]
  public static extern int FsgModel_WordId(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_FsgModel_WordAdd")]
  public static extern int FsgModel_WordAdd(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_FsgModel_TransAdd")]
  public static extern void FsgModel_TransAdd(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_FsgModel_NullTransAdd")]
  public static extern int FsgModel_NullTransAdd(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_FsgModel_TagTransAdd")]
  public static extern int FsgModel_TagTransAdd(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_FsgModel_AddSilence")]
  public static extern int FsgModel_AddSilence(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_FsgModel_AddAlt")]
  public static extern int FsgModel_AddAlt(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_FsgModel_Writefile")]
  public static extern void FsgModel_Writefile(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_new_JsgfRule")]
  public static extern global::System.IntPtr new_JsgfRule();

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_JsgfRule_FromIter")]
  public static extern global::System.IntPtr JsgfRule_FromIter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_JsgfRule_GetName")]
  public static extern string JsgfRule_GetName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_JsgfRule_IsPublic")]
  public static extern bool JsgfRule_IsPublic(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_delete_JsgfRule")]
  public static extern void delete_JsgfRule(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModel_FromIter")]
  public static extern global::System.IntPtr NGramModel_FromIter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_new_NGramModel__SWIG_0")]
  public static extern global::System.IntPtr new_NGramModel__SWIG_0(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_new_NGramModel__SWIG_1")]
  public static extern global::System.IntPtr new_NGramModel__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_delete_NGramModel")]
  public static extern void delete_NGramModel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModel_Write")]
  public static extern void NGramModel_Write(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModel_StrToType")]
  public static extern int NGramModel_StrToType(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModel_TypeToStr")]
  public static extern string NGramModel_TypeToStr(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModel_Casefold")]
  public static extern void NGramModel_Casefold(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModel_Size")]
  public static extern int NGramModel_Size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModel_AddWord")]
  public static extern int NGramModel_AddWord(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModel_Prob")]
  public static extern int NGramModel_Prob(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_new_LogMath")]
  public static extern global::System.IntPtr new_LogMath();

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_delete_LogMath")]
  public static extern void delete_LogMath(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_LogMath_Exp")]
  public static extern double LogMath_Exp(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_new_NGramModelSetIterator")]
  public static extern global::System.IntPtr new_NGramModelSetIterator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_delete_NGramModelSetIterator")]
  public static extern void delete_NGramModelSetIterator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModelSetIterator_MoveNext")]
  public static extern bool NGramModelSetIterator_MoveNext(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModelSetIterator_Reset")]
  public static extern void NGramModelSetIterator_Reset(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModelSetIterator_GetCurrent")]
  public static extern global::System.IntPtr NGramModelSetIterator_GetCurrent(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_new_JsgfIterator")]
  public static extern global::System.IntPtr new_JsgfIterator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_delete_JsgfIterator")]
  public static extern void delete_JsgfIterator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_JsgfIterator_MoveNext")]
  public static extern bool JsgfIterator_MoveNext(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_JsgfIterator_Reset")]
  public static extern void JsgfIterator_Reset(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_JsgfIterator_GetCurrent")]
  public static extern global::System.IntPtr JsgfIterator_GetCurrent(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModelSet_GetEnumerator")]
  public static extern global::System.IntPtr NGramModelSet_GetEnumerator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_new_NGramModelSet")]
  public static extern global::System.IntPtr new_NGramModelSet(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_delete_NGramModelSet")]
  public static extern void delete_NGramModelSet(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModelSet_Count")]
  public static extern int NGramModelSet_Count(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModelSet_Add")]
  public static extern global::System.IntPtr NGramModelSet_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, float jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModelSet_Select")]
  public static extern global::System.IntPtr NGramModelSet_Select(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModelSet_Lookup")]
  public static extern global::System.IntPtr NGramModelSet_Lookup(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_NGramModelSet_Current")]
  public static extern string NGramModelSet_Current(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_Jsgf_GetEnumerator")]
  public static extern global::System.IntPtr Jsgf_GetEnumerator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_new_Jsgf")]
  public static extern global::System.IntPtr new_Jsgf(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_delete_Jsgf")]
  public static extern void delete_Jsgf(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_Jsgf_GetName")]
  public static extern string Jsgf_GetName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_Jsgf_GetRule")]
  public static extern global::System.IntPtr Jsgf_GetRule(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpocketsphinxwrap", EntryPoint="CSharp_Jsgf_BuildFsg")]
  public static extern global::System.IntPtr Jsgf_BuildFsg(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, float jarg4);
}

}
